### ISSUE TITLE
网络提示问题

### ISSUE THREAD

**Issue by 429329513wanting** [guolindev/coolweatherjetpack#10]
郭神你好！，这个架构，如果统一封装处理网络loading呢，看了半天不知道加在哪里.

**Comment by guolindev** [comment]
没太看明白你的意思。

**Comment by 429329513wanting** [comment]
就是请求时显示网络进度，请求结束时dismiss网络提示？是在每个viewmodel里处理？

**Comment by guolindev** [comment]
ui操作当然要放到activity或者fragment里面，viewmodel不会持有任何控件的引用，所以肯定不能放在viewmodel里面。你如果想统一封装的话，可以考虑放到BaseActivity里面。
