### ISSUE TITLE
求指导，InjectorUtil类和WeatherModelFactory类有什么作用？

### ISSUE THREAD

**Issue by chengjuechao** [guolindev/coolweatherjetpack#13]
我在 WeatherActivity 中 这样写 `viewModel = ViewModelProviders.of(this, ViewModelProvider.NewInstanceFactory()).get(WeatherViewModel::class.java)`
不就不需要InjectorUtil类和WeatherModelFactory类了么，请指导哇

**Comment by chengjuechao** [comment]
哦哦  知道了  `WeatherModelFactory` 是为了传参吧   但是项目里吧`WeatherRepository`写成了单例  应该就不需要传参了吧

**Comment by guolindev** [comment]
是的，也可以用单例实现。
