### ISSUE TITLE
是否少提交了databinding目录中的资源

### ISSUE THREAD

**Issue by YeJiashen** [guolindev/coolweatherjetpack#17]
我在导入了项目后这几个类报红, 经查找没有找到databinding目录 ;
而在gradle中的依赖文件中也没有看到类似包名的依赖 ;
com.coolweather.coolweatherjetpack.databinding.ForecastItemBinding;
com.coolweather.coolweatherjetpack.databinding.SimpleItemBinding;
com.coolweather.coolweatherjetpack.databinding.ChooseAreaBindingImpl;
com.coolweather.coolweatherjetpack.databinding.ChooseAreaBindingImpl;

**Comment by guolindev** [comment]
这几个类是启用data binding编译后自动生成的，并不是手动编译的类。
