### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by TianGuisen** [guolindev/coolweatherjetpack#19]
看到choose_area.xml中backButton点击事件是调用的是ChooseAreaViewModel的onBack()方法..
假如需要在这个方法中进行跳转界面或者销毁界面等UI操作,应该怎么写呢.只能在ViewModel中再写一个livedata改变状态,activity获取引用观察变化操作UI吗.

**Comment by guolindev** [comment]
跳转界面或者销毁界面，你直接写在activity里面就行了，不管是livedata还是databinding，它们的响应式编程都建立在数据变动的基础上，像这种没有数据交互的场景，只是点击按钮，UI进行响应，直接正常去写就行了，不用非得去考虑怎么监听数据状态变化之类的。
