### ISSUE TITLE
viewmodel中处理了ui操作?

### ISSUE THREAD

**Issue by beanu** [guolindev/coolweatherjetpack#26]
是不是不应该在viewmodel类中处理去处理UI的逻辑?

**Comment by madreain** [comment]
欢迎使用 https://github.com/madreain/AACHulk，并提出相关问题

**Comment by guolindev** [comment]
ViewModel中是不应该进行ui操作，因为不能持有Activity的引用，但是这个项目中并没有在ViewModel中进行UI操作，ViewModel只是处理了Databinding的事件而已，所有UI操作都是基于ViewModel的处理接口由Databinding自动进行的。
