### ISSUE TITLE
勘误，文字拼写错误

### ISSUE THREAD

**Issue by shikechen** [guolindev/coolweatherjetpack#28]
郭婶~发现2处书写错误，不知道能不能看到？
1、架构图上的WeatherNetworkSourse中的Sourse书写错误 应为 Source；
2、架构图下第6段“表示是的” 应为 表示的是。

**Comment by plain-dev** [comment]
@shikechen 建议去[图灵社区](https://www.ituring.com.cn/book/2744)反馈

**Comment by shikechen** [comment]
@plain-dev 这个是当前项目的README介绍的问题啊

**Comment by guolindev** [comment]
原图找不着了，尴尬，反正不是什么大问题，就这样凑合着看吧
