### ISSUE TITLE
和风天气接口问题

### ISSUE THREAD

**Issue by SRmonologue** [guolindev/coolweatherjetpack#3]
这里是用的老版本的接口吗？新注册的用户好像用不了老版本的接口。
https://www.heweather.com/documents/api/x3/url

**Comment by 603751448** [comment]
我也遇到了这个问题，显示 获取天气信息失败

**Comment by 603751448** [comment]
> 我也遇到了这个问题，显示获取天气信息失败

尝试使用免费用户的格式，依旧出现显示   “获取天气信息失败”

**Comment by SilasGao** [comment]
注册后拿到了key。获取天气信息失败

**Comment by guolindev** [comment]
看来和风天气都更新接口了，刚才翻了一下和气的文档说明，看到了这句话

> 请注意，2018年以后新注册的用户仅能使用s6版本的接口服务。

不过没关系，等我更新一下中间服务器的代码就行了，可以先用这个key测试一下 45dd25f63300445e967b461d2037e4f9 ，不过使用次数有限，每天只能请求1000次。

**Comment by guolindev** [comment]
提交了默认的Key，更新一下即可。
