### ISSUE TITLE
com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by SupingX** [guolindev/coolweatherjetpack#4]
查询天气得时候，会报这个错误。由于不了解kotlin，不知道怎么调试。可能是返回得json有问题
WeatherRepository#requestWeather#onFailure

**Comment by SupingX** [comment]
另外有没有java版 - -、

**Comment by guolindev** [comment]
java版本在这里 https://github.com/guolindev/coolweather
另外你可以再更新一下代码试试，我提交了一个默认的Key。

**Comment by SupingX** [comment]
java版本- -、但是没有mvvm
