### ISSUE TITLE
请教一下，为什么没有给网络请求，做dispose操作

### ISSUE THREAD

**Issue by zii4914** [guolindev/coolweatherjetpack#6]
一般来说，在页面onDestory的时候都会取消当前正在进行的网络请求，但是我没有在这个项目找到这类操作。不取消网络请求的话，不会导致内存泄漏吗，比如页面已经关闭，请求才完成，完成时候调用关闭loading弹框，但是这时候页面已经销毁，就导致了loading弹框leak异常

**Comment by guolindev** [comment]
因为这是MVVM架构的项目，Activity的引用不被ViewModel持有，LiveData也可以自感知生命周期，当你的页面关闭了之后，网络请求的结果LiveData根本就不会回调的，所以你说的这个异常是不可能发生的。

**Comment by wfqdroid** [comment]
可以看下LiveData的observe方法，里面已经做了判断
